framework:
    router:
        utf8: true
#authentication_token:
#    path: /authentication_token
#    methods: ['POST']
        # Configure how to generate URLs in non-HTTP contexts, such as CLI commands.
        # See https://symfony.com/doc/current/routing.html#generating-urls-in-commands
        #default_uri: http://localhost
